# Generated by Django 5.2.1 on 2025-06-02 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Antibiotics', 'Antibiotics'), ('Painkillers', 'Painkillers'), ('Antivirals', 'Antivirals'), ('Antifungals', 'Antifungals'), ('Antiparasitics', 'Antiparasitics'), ('Antipyretics', 'Antipyretics'), ('Antidepressants', 'Antidepressants'), ('Antipsychotics', 'Antipsychotics'), ('Antiepileptics', 'Antiepileptics'), ('Antimalarials', 'Antimalarials'), ('Anthelmintics', 'Anthelmintics'), ('Antibacterial', 'Antibacterial'), ('Antiviral', 'Antiviral'), ('Antifungal', 'Antifungal'), ('Antiparasitic', 'Antiparasitic'), ('Antipyretic', 'Antipyretic'), ('Antidepressant', 'Antidepressant'), ('Antipsychotic', 'Antipsychotic'), ('Antiepileptic', 'Antiepileptic'), ('Antimalarial', 'Antimalarial'), ('Anthelmintic', 'Anthelmintic'), ('Autres', 'Autres')], max_length=100)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('forme', models.CharField(blank=True, max_length=100, null=True)),
                ('laboratoire', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicaments/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Medication Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('stock_quantity', models.PositiveIntegerField(verbose_name='Stock Quantity')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medications/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='App.category')),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Customer Phone')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile', 'Mobile Payment')], default='cash', max_length=20, verbose_name='Payment Method')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.medication')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='App.purchase')),
            ],
            options={
                'verbose_name': 'Purchase Item',
                'verbose_name_plural': 'Purchase Items',
            },
        ),
    ]
